spring:
  application:
    name: spring-cloud-eureka-feign-client
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 
feign:
       hystrix:
                enabled: true